"""
Django settings for Project project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o3#a@^)j09&e_3%y6*b-72gjgp!ey71ug16op-2m4cb0an6idk'
SECURE_KEY = 'U0VDVVJJVFlfS0VZX0ZPUl9BVVRIRU5USUNBVElPTg=='
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    #'daphne',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.redirects',
    # 'django.contrib.sites',
    'API',
    'Register',
    'Link',
    'View',
    'Update',
    'Delete',
    'mqtt',
    'rest_framework',
    'channels',
]

REST_FRAMEWORK = {
    'DATETIME_FORMAT': "%Y-%m-%d %H:%M:%S",
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
]

ROOT_URLCONF = 'Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Project.wsgi.application'
ASGI_APPLICATION = 'Project.asgi.application'
#WEBSOCKET_CLOSE_TIMEOUT = 30

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
#This setting determines how long the database connection will be kept open
#CONN_MAX_AGE=600 -> 10mits
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hes_exp',
        'USER': 'meter',
        'PASSWORD': 'REConnect123@',
        'HOST': '52.12.47.10',
        'CONN_MAX_AGE': 3200,
         'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

MQTT_BROKER_HOST = "iotrd.grid.reconnectenergy.com" #"iotrd.grid.reconnectenergy.com" #ipv6 address
MQTT_BROKER_PORT = 1883
MQTT_CLIENT_ID = "" #"DCU-E70-RECONNECT"
MQTT_USERNAME ="reconnect"
MQTT_PASSWORD ="reconnect"
MQTT_TOPIC1 =  "synergy/mqtt/dcu/meterdata"
#MQTT_TOPIC2 =  "synergy/mqtt/dcu/dcuhealth"
MQTT_KEEPALIVE = 60

'''MQTT_BROKER_HOST = "122.176.28.40" #ipv4 address
MQTT_BROKER_PORT = 1883
MQTT_CLIENT_ID = ""
MQTT_USERNAME ="reconnect"
MQTT_PASSWORD ="reconnect"
MQTT_TOPIC = "synergy/mqtt/dcu/meterdata"
MQTT_KEEPALIVE = 60

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('localhost', 6379)],
        },
    },
} 
MQTT_TOPIC =  "synergy/mqtt/dcu/meterdataaths"
MQTT_KEEPALIVE = 60'''


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
